### ISSUE TITLE
Timer/Cooldown suggestion

### ISSUE THREAD

**Issue by GavoTrav** [twitch-irc/twitch-irc#100]
Would you guys be able to add something like a timer function for commands? like a command can be used every 120 seconds or something? I mean like a command cooldown which can be bypassed by mods+ ?

Would be great if possible!

**Comment by mikethemadkiwi** [comment]
This is something you can easily do on your end gavotrav.
a simple variable : 

var justRan = false;

if the command is run, set it to true, and if true, don't output the code...

if( justRan == true ) { you just ran this code}
else{  
var ttimer = setTimeout(function(){ justRan == false}, 120000)
// I CAN RUN THE CODE HERE
}
sloppy code, but you get my point...

**Comment by Schmoopiie** [comment]
Hello @GavoTrav!

Unfortunatly, as @mikethemadkiwi said, it is more likely going to be on your end. However, if you need help with your code, there will be a forums available in a few days for twitch-irc. I am very busy lately because I am doing a complete overhaul of the module, I am changing the protocol and will be using Websockets instead. I will keep you guys updated on GitHub and Twitter.

Thanks!
