### ISSUE TITLE
Integrate new whispers?

### ISSUE THREAD

**Issue by GavoTrav** [twitch-irc/twitch-irc#103]
Will there be some sort of integration for new whispers feature? they talked about how it can be done here: http://discuss.dev.twitch.tv/t/whispers-on-irc/2459/3

**Comment by Schmoopiie** [comment]
They are planning to move it to a new system and it won't be part of the TMI, so I'm not sure to be honest.

**Comment by mikethemadkiwi** [comment]
it was my understanding from a dev that the whispers are in fact just the irc standard Privmsg. would i be incorrect in assuming that a listener for that event would capture the whispers?

**Comment by Schmoopiie** [comment]
Twitch is planning to move it away from IRC and use a different protocol that is why we will not support this. I will add support to it if they plan to use Websockets or EventSource. I doubt we (the devs) will be able to use this feature in the future and that is why I don't see the point of using this. As Brildum said: ``We purposely made whispers convoluted for IRC integration because we didn't want users and bot developers to become reliant on receiving user-to-user messages via IRC. We have plans to stop using TMI to send user-to-user messages and instead use a new system (and protocol) entirely. When will this happen? Hopefully in the few months.``

**Comment by EfficiencyVI** [comment]
If anybody want to do that, it is pretty easy to do without changing much in the library. Go to your nodejs modules/twitch-irc/libraries/client.js and search this line:

```javascript
            /* Received message on a channel */
            case 'PRIVMSG':
```

change it to

```javascript
            /* Received message on a channel */
            case 'PRIVMSG':
            case 'WHISPER':
```

Private messages are not send over IRC chat so you will need a second instance. Connect like this:

```javascript
    var twitch = new _twitch.client({
        …
        connection: {
            serverType: 'groups'
        },
        …
    });
```

and add a listener as usual:

```javascript
    twitch.addListener('chat', twitchEventChat);
```

Every private message will be handled like a normal chat message. You can use that to send it to your main bot to process e. g. commands. Sending messages is just a

```javascript
    twitch.say(channel, "/w Booop!"));
```

The channel you send it over does not matter as the private message will be delivered to any chat the user is in. The channel of an incoming message is always the channel of the receiving username so don't rely on it. Send the message to a channel you are connected to. Hopes that helps some people.

**Comment by mikethemadkiwi** [comment]
Bravo, excellent work around.
