### ISSUE TITLE
Throwing Error: Cannot read property 'tags' of null

### ISSUE THREAD

**Issue by larzuk91** [twitch-irc/twitch-irc#106]
Hi, I'm not sure if this error is a problem of the project or is just mine, but would be nice to know why it is throwing it some times (like once every 10 runs)

![error](https://cloud.githubusercontent.com/assets/3451985/8137981/d6684342-110c-11e5-8736-dae130ea1d15.jpg)

**Comment by Schmoopiie** [comment]
Hey @larzuk91!

Twitch is changing some of their servers to Websockets and that is why it is throwing this error, choose a server that is working and stick to it for now ([use preferredServer and preferredPort](http://www.twitch-irc.com/docs/twitch-irc/Configuration)), do **not** use irc.twitch.tv because it is returning some Websocket servers too. I am working very hard to change the protocol of the module, I am doing a complete overhaul actually.. it will be available as a standalone script for browsers supporting Websockets and also a node.js / io.js module.

Thanks!

**Comment by larzuk91** [comment]
I'll do that.
Thanks bro!
