### ISSUE TITLE
client.say does not re-emit a chat message

### ISSUE THREAD

**Issue by celluj34** [twitch-irc/twitch-irc#60]
When using your library, I can send a message like so:

```
socket.on("outgoingMessage", function(data) {
    client.say(data.channel, data.message);
});
```

I would expect that I would immediately receive an incoming message wit the relevant user information (badges, status, color, etc), but I do not. I can manually emit my own incoming message, but where would I get the special information about myself?

```
socket.on("outgoingMessage", function(data) {
	client.say(data.channel, data.message);

	socket.emit("incomingMessage", {
		name: client.myself,
		attributes: user.special, // ?
		color: user.color, // ?
		message: data.message,
		channel: data.channel
	});
});
```

**Comment by Schmoopiie** [comment]
Sorry for the delayed answer, I am on vacation.. At the moment there is no possible way to get your own informations such as the username color and special status. The reason why it is not yet possible is because we are using IRCv3 tags and the informations given when joining a channel isn't reliable yet.

At the moment there is no ETA, but expect this feature to be available in one of the next versions of twitch-irc.

**Comment by celluj34** [comment]
No worries! It's not a huge deal.

Could it be an option in the client settings to re-emit a message, with a default to false? That way current implementations can retain functionality, while I can choose to enable it?

**Comment by celluj34** [comment]
One last question, sorry, will this also re-emit Actions?

**Comment by Schmoopiie** [comment]
Yes it does, I will bump the module version later though.. I still need to work on some stuff :smile:
