### ISSUE TITLE
Mod function with a timed re-check causing EventEmitter memory leaks

### ISSUE THREAD

**Issue by macharborguy** [twitch-irc/twitch-irc#84]
The error in question... 
 
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit. 
Trace 
    at addListener (events.js:179:15)at once (events.js:204:8) 
    at client.mods (/myApp/node_modules/twitch-irc/libraries/client.js:775:14) 
    at Object.modUpdater (/myApp/lib/chatManager.js:360:11) 
    at updateMods (/myApp/lib/chatManager.js:363:10) 
    at Timer.listOnTimeout (timers.js:110:15) 
```

To make sure the bot has the latest list of mods, i have a function that runs the .mods() function of Twitch-IRC, and assigns a variable to setTimeout.  That timeout will rerun .mods() in 60 seconds, clear and reset the timeout to be run again in 60 seconds.

It appears that the .mods() command is creating a listeners with each run, at line 775 of client.js, but may not be clearing the listener after it has been run.

here is my updater code...

```
// variable to hold the setTimeout
var timerHolder = null;

var updaterFunction = function () {
    irc.mods('channelName');
    
    // make sure the timerHolder is cleared and null (may be overkill)
    clearTimeout(timerHolder);
    timerHolder = null;
    
    // set timerHolder to rerun this function in 1 minute
    timerHolder = setTimeout(function(){
        updaterFunction();
    },60000);
};
```

if any additional information is required, please let me know and I will provide what I can

**Comment by celluj34** [comment]
related to #80?

**Comment by Schmoopiie** [comment]
Hello,

The ``warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.`` warning message is **normal** when you are using a lot of listeners, however [we have disabled it](https://github.com/twitch-irc/twitch-irc/blob/master/libraries/client.js#L41) because it is not a memory leak. The event listener is added to fire [only once](https://github.com/twitch-irc/twitch-irc/blob/master/libraries/client.js#L831). However, I am not sure why you are getting this message as it was supposed to be disabled.

**Comment by macharborguy** [comment]
It appears that I am using an older version, 1.2.5.  i will update and see if that fixes things.
